// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, name, api_key, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, name, api_key, created_at, updated_at, webhook_url
`

type CreateClientParams struct {
	ID     pgtype.UUID
	Name   string
	ApiKey pgtype.UUID
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.ID, arg.Name, arg.ApiKey)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const getClientByApiKey = `-- name: GetClientByApiKey :one
SELECT id, name, api_key, created_at, updated_at, webhook_url FROM clients WHERE api_key = $1
`

func (q *Queries) GetClientByApiKey(ctx context.Context, apiKey pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByApiKey, apiKey)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const getClientById = `-- name: GetClientById :one
SELECT id, name, api_key, created_at, updated_at, webhook_url FROM clients WHERE id = $1
`

func (q *Queries) GetClientById(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientById, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, api_key, created_at, updated_at, webhook_url FROM clients ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListClientsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET name = $1, updated_at = NOW() WHERE id = $2 RETURNING id, name, api_key, created_at, updated_at, webhook_url
`

type UpdateClientParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient, arg.Name, arg.ID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const updateClientWebhookURL = `-- name: UpdateClientWebhookURL :one
UPDATE clients
SET webhook_url = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, name, api_key, created_at, updated_at, webhook_url
`

type UpdateClientWebhookURLParams struct {
	WebhookUrl pgtype.Text
	ID         pgtype.UUID
}

func (q *Queries) UpdateClientWebhookURL(ctx context.Context, arg UpdateClientWebhookURLParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientWebhookURL, arg.WebhookUrl, arg.ID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
	)
	return i, err
}
