// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: funding_sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFundingSource = `-- name: CreateFundingSource :one
INSERT INTO funding_sources (id, client_id, name, type, payment_account_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, client_id, name, type, payment_account_id, created_at, updated_at
`

type CreateFundingSourceParams struct {
	ID               pgtype.UUID
	ClientID         pgtype.UUID
	Name             string
	Type             string
	PaymentAccountID string
}

func (q *Queries) CreateFundingSource(ctx context.Context, arg CreateFundingSourceParams) (FundingSource, error) {
	row := q.db.QueryRow(ctx, createFundingSource,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Type,
		arg.PaymentAccountID,
	)
	var i FundingSource
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Type,
		&i.PaymentAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFundingSourceById = `-- name: GetFundingSourceById :one
SELECT id, client_id, name, type, payment_account_id, created_at, updated_at FROM funding_sources WHERE id = $1
`

func (q *Queries) GetFundingSourceById(ctx context.Context, id pgtype.UUID) (FundingSource, error) {
	row := q.db.QueryRow(ctx, getFundingSourceById, id)
	var i FundingSource
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Type,
		&i.PaymentAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFundingSourcesByClientId = `-- name: ListFundingSourcesByClientId :many
SELECT id, client_id, name, type, payment_account_id, created_at, updated_at FROM funding_sources WHERE client_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListFundingSourcesByClientIdParams struct {
	ClientID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListFundingSourcesByClientId(ctx context.Context, arg ListFundingSourcesByClientIdParams) ([]FundingSource, error) {
	rows, err := q.db.Query(ctx, listFundingSourcesByClientId, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FundingSource
	for rows.Next() {
		var i FundingSource
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Type,
			&i.PaymentAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFundingSource = `-- name: UpdateFundingSource :one
UPDATE funding_sources SET name = $1, type = $2, payment_account_id = $3, updated_at = NOW() WHERE id = $4 RETURNING id, client_id, name, type, payment_account_id, created_at, updated_at
`

type UpdateFundingSourceParams struct {
	Name             string
	Type             string
	PaymentAccountID string
	ID               pgtype.UUID
}

func (q *Queries) UpdateFundingSource(ctx context.Context, arg UpdateFundingSourceParams) (FundingSource, error) {
	row := q.db.QueryRow(ctx, updateFundingSource,
		arg.Name,
		arg.Type,
		arg.PaymentAccountID,
		arg.ID,
	)
	var i FundingSource
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Type,
		&i.PaymentAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
