// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: funding_sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFundingSource = `-- name: CreateFundingSource :one
INSERT INTO funding_sources (id, client_id, name, type, payment_account_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, name, type, payment_account_id, status, created_at, updated_at
`

type CreateFundingSourceParams struct {
	ID               pgtype.UUID
	ClientID         pgtype.UUID
	Name             string
	Type             string
	PaymentAccountID string
}

func (q *Queries) CreateFundingSource(ctx context.Context, arg CreateFundingSourceParams) (FundingSource, error) {
	row := q.db.QueryRow(ctx, createFundingSource,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Type,
		arg.PaymentAccountID,
	)
	var i FundingSource
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Type,
		&i.PaymentAccountID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFundingSourceByClientID = `-- name: GetFundingSourceByClientID :one
SELECT id, client_id, name, type, payment_account_id, status, created_at, updated_at
FROM funding_sources
WHERE client_id = $1 AND id = $2
`

type GetFundingSourceByClientIDParams struct {
	ClientID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetFundingSourceByClientID(ctx context.Context, arg GetFundingSourceByClientIDParams) (FundingSource, error) {
	row := q.db.QueryRow(ctx, getFundingSourceByClientID, arg.ClientID, arg.ID)
	var i FundingSource
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Type,
		&i.PaymentAccountID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFundingSourcesByClientID = `-- name: ListFundingSourcesByClientID :many
SELECT id, client_id, name, type, payment_account_id, status, created_at, updated_at
FROM funding_sources
WHERE client_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListFundingSourcesByClientIDParams struct {
	ClientID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListFundingSourcesByClientID(ctx context.Context, arg ListFundingSourcesByClientIDParams) ([]FundingSource, error) {
	rows, err := q.db.Query(ctx, listFundingSourcesByClientID, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FundingSource
	for rows.Next() {
		var i FundingSource
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Type,
			&i.PaymentAccountID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
