// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (key, client_id, request_hash, payout_id)
VALUES ($1, $2, $3, $4)
RETURNING key, client_id, request_hash, payout_id, created_at
`

type CreateIdempotencyKeyParams struct {
	Key         string
	ClientID    pgtype.UUID
	RequestHash string
	PayoutID    pgtype.UUID
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.ClientID,
		arg.RequestHash,
		arg.PayoutID,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ClientID,
		&i.RequestHash,
		&i.PayoutID,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, client_id, request_hash, payout_id, created_at
FROM idempotency_keys
WHERE client_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	ClientID pgtype.UUID
	Key      string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ClientID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ClientID,
		&i.RequestHash,
		&i.PayoutID,
		&i.CreatedAt,
	)
	return i, err
}
