// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID         pgtype.UUID
	Name       string
	ApiKey     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	WebhookUrl pgtype.Text
}

type FundingSource struct {
	ID               pgtype.UUID
	ClientID         pgtype.UUID
	Name             string
	Type             string
	PaymentAccountID string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type IdempotencyKey struct {
	Key         string
	ClientID    pgtype.UUID
	RequestHash string
	PayoutID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type OutboxEvent struct {
	ID          pgtype.UUID
	EventType   string
	Payload     []byte
	Status      string
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	EntityID    pgtype.UUID
	ClaimedAt   pgtype.Timestamptz
}

type Payout struct {
	ID                 pgtype.UUID
	ClientID           pgtype.UUID
	FundingSourceID    pgtype.UUID
	Amount             pgtype.Numeric
	Currency           string
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	FailureReason      pgtype.Text
	ExternalID         pgtype.Text
	RecipientName      pgtype.Text
	RecipientAccountID pgtype.Text
}

type WebhookDelivery struct {
	ID           pgtype.UUID
	PayoutID     pgtype.UUID
	ClientID     pgtype.UUID
	TargetUrl    string
	Payload      []byte
	Status       string
	AttemptCount int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
