// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (event_type, entity_id, payload)
VALUES ($1, $2, $3)
RETURNING id, event_type, payload, status, created_at, processed_at, entity_id
`

type CreateOutboxEventParams struct {
	EventType string
	EntityID  pgtype.UUID
	Payload   []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.EntityID, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.EntityID,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, payload, status, created_at, processed_at, entity_id FROM outbox_events WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.EntityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventAsProcessed = `-- name: MarkOutboxEventAsProcessed :one
UPDATE outbox_events SET status = 'processed', processed_at = NOW() WHERE id = $1 RETURNING id, event_type, payload, status, created_at, processed_at, entity_id
`

func (q *Queries) MarkOutboxEventAsProcessed(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventAsProcessed, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.EntityID,
	)
	return i, err
}
