// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (id, client_id, funding_source_id, amount, currency, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, client_id, funding_source_id, amount, currency, status, created_at, updated_at
`

type CreatePayoutParams struct {
	ID              pgtype.UUID
	ClientID        pgtype.UUID
	FundingSourceID pgtype.UUID
	Amount          pgtype.Numeric
	Currency        string
	Status          string
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.ID,
		arg.ClientID,
		arg.FundingSourceID,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FundingSourceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutById = `-- name: GetPayoutById :one
SELECT id, client_id, funding_source_id, amount, currency, status, created_at, updated_at FROM payouts WHERE id = $1
`

func (q *Queries) GetPayoutById(ctx context.Context, id pgtype.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutById, id)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FundingSourceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayoutsByClientId = `-- name: ListPayoutsByClientId :many
SELECT id, client_id, funding_source_id, amount, currency, status, created_at, updated_at FROM payouts WHERE client_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPayoutsByClientIdParams struct {
	ClientID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPayoutsByClientId(ctx context.Context, arg ListPayoutsByClientIdParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByClientId, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.FundingSourceID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayoutStatus = `-- name: UpdatePayoutStatus :one
UPDATE payouts SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING id, client_id, funding_source_id, amount, currency, status, created_at, updated_at
`

type UpdatePayoutStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatus, arg.Status, arg.ID)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FundingSourceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
