// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    payout_id,
    client_id,
    target_url,
    payload,
    status,
    attempt_count
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payout_id, client_id, target_url, payload, status, attempt_count, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	PayoutID     pgtype.UUID
	ClientID     pgtype.UUID
	TargetUrl    string
	Payload      []byte
	Status       string
	AttemptCount int32
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.PayoutID,
		arg.ClientID,
		arg.TargetUrl,
		arg.Payload,
		arg.Status,
		arg.AttemptCount,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PayoutID,
		&i.ClientID,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, payout_id, client_id, target_url, payload, status, attempt_count, created_at, updated_at
FROM webhook_deliveries
WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id pgtype.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PayoutID,
		&i.ClientID,
		&i.TargetUrl,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveriesByPayoutID = `-- name: ListWebhookDeliveriesByPayoutID :many
SELECT id, payout_id, client_id, target_url, payload, status, attempt_count, created_at, updated_at
FROM webhook_deliveries
WHERE payout_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWebhookDeliveriesByPayoutID(ctx context.Context, payoutID pgtype.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByPayoutID, payoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.PayoutID,
			&i.ClientID,
			&i.TargetUrl,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
